name: e_learning_app
description: "E-Learning application for courses and tests"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  go_router: ^15.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  flutter_animate: ^4.5.0
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  hive_generator: ^2.0.1
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
