// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIK0hf2-AF8xULd0n3-AWRo8zNBsZxMoU',
    appId: '1:463774702071:web:6ac5e55b7a63039b80f6f2',
    messagingSenderId: '463774702071',
    projectId: 'elearningapp-70aba',
    authDomain: 'elearningapp-70aba.firebaseapp.com',
    storageBucket: 'elearningapp-70aba.firebasestorage.app',
    measurementId: 'G-R59HJE1L62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTxc6jyQi5BXZ-PxqSImmT2F_U0sSZtdI',
    appId: '1:463774702071:android:ca3cf01d933dfbfa80f6f2',
    messagingSenderId: '463774702071',
    projectId: 'elearningapp-70aba',
    storageBucket: 'elearningapp-70aba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1ILMkj-XbV-TABufV6TYXo70_pBFsH38',
    appId: '1:463774702071:ios:11e279057403d99a80f6f2',
    messagingSenderId: '463774702071',
    projectId: 'elearningapp-70aba',
    storageBucket: 'elearningapp-70aba.firebasestorage.app',
    iosBundleId: 'com.example.eLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1ILMkj-XbV-TABufV6TYXo70_pBFsH38',
    appId: '1:463774702071:ios:11e279057403d99a80f6f2',
    messagingSenderId: '463774702071',
    projectId: 'elearningapp-70aba',
    storageBucket: 'elearningapp-70aba.firebasestorage.app',
    iosBundleId: 'com.example.eLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIK0hf2-AF8xULd0n3-AWRo8zNBsZxMoU',
    appId: '1:463774702071:web:c337b6cef031aab280f6f2',
    messagingSenderId: '463774702071',
    projectId: 'elearningapp-70aba',
    authDomain: 'elearningapp-70aba.firebaseapp.com',
    storageBucket: 'elearningapp-70aba.firebasestorage.app',
    measurementId: 'G-872ZZEWCYY',
  );
}
